#if defined _WIN32
extern unsigned char resource_root[];

#define   ACTIVITY_BIN                            (void *)(resource_root + 0x000004b8)
#define   APP_LIST3_BIN                           (void *)(resource_root + 0x000a19f8)
#define   CURTAIN_RECT_248_385_BIN                (void *)(resource_root + 0x000a2cf8)
#define   SAT_BIN                                 (void *)(resource_root + 0x000d16f8)
#define   SUN_BIN                                 (void *)(resource_root + 0x000d2578)
#define   THU_BIN                                 (void *)(resource_root + 0x000d33f8)
#define   TUE_BIN                                 (void *)(resource_root + 0x000d4278)
#define   WED_BIN                                 (void *)(resource_root + 0x000d50f8)
#define   WHATSAPP_BIN                            (void *)(resource_root + 0x000d5f78)
#define   ADD_BIN                                 (void *)(resource_root + 0x000d7838)
#define   ASSEMBLY_BIN                            (void *)(resource_root + 0x000d7b78)
#define   AUDIO_FREQUENCY_BIN                     (void *)(resource_root + 0x000d7bf8)
#define   CALLING_0_BIN                           (void *)(resource_root + 0x000dcbb8)
#define   CENTIGRADE_BIN                          (void *)(resource_root + 0x000de738)
#define   CIRCLE_BIN                              (void *)(resource_root + 0x000ded78)
#define   CLOSE_BIN                               (void *)(resource_root + 0x000e0638)
#define   DATA_BIN                                (void *)(resource_root + 0x000e8f38)
#define   DELETE_BIN                              (void *)(resource_root + 0x000e9a78)
#define   DIRECTION_BIN                           (void *)(resource_root + 0x000ea938)
#define   FACEBOOK_BIN                            (void *)(resource_root + 0x000eb538)
#define   FRI_BIN                                 (void *)(resource_root + 0x000eceb8)
#define   HEART_RATE_BIN                          (void *)(resource_root + 0x000edd38)
#define   INSTAGRAM_BIN                           (void *)(resource_root + 0x000ee9f8)
#define   LNE_BIN                                 (void *)(resource_root + 0x000f02b8)
#define   MAP_BIN                                 (void *)(resource_root + 0x000f1b78)
#define   MESSAGE_0_BIN                           (void *)(resource_root + 0x000f7878)
#define   MESSAGE_1_BIN                           (void *)(resource_root + 0x000f9138)
#define   MESSAGE_2_BIN                           (void *)(resource_root + 0x000fa9f8)
#define   MESSAGE_3_BIN                           (void *)(resource_root + 0x000fc2b8)
#define   MESSAGE_APP1L_BIN                       (void *)(resource_root + 0x00107e78)
#define   MESSAGE_MUS_BIN                         (void *)(resource_root + 0x0011d978)
#define   MESSAGE_WEIXIN_BIN                      (void *)(resource_root + 0x00129538)
#define   MON_BIN                                 (void *)(resource_root + 0x0013edf8)
#define   MUSIC_0_BIN                             (void *)(resource_root + 0x0013fc78)
#define   MUSIC_1_BIN                             (void *)(resource_root + 0x00140a38)
#define   NOTIFY_BIN                              (void *)(resource_root + 0x001432f8)
#define   RECT_100_127_BIN                        (void *)(resource_root + 0x00175d38)
#define   RECT_110_108_BIN                        (void *)(resource_root + 0x0017c0b8)
#define   RECT_146_50_BIN                         (void *)(resource_root + 0x00181db8)
#define   RECT_160_385_BIN                        (void *)(resource_root + 0x001856f8)
#define   RECT_228_64_BIN                         (void *)(resource_root + 0x001a3878)
#define   RECT_300_126_BIN                        (void *)(resource_root + 0x001aaab8)
#define   RECT_300_127_BIN                        (void *)(resource_root + 0x001bd238)
#define   RECT_300_80_BIN                         (void *)(resource_root + 0x001cfbf8)
#define   RECT_350_348_BIN                        (void *)(resource_root + 0x001db7b8)
#define   RING_BIN                                (void *)(resource_root + 0x00226578)
#define   SIRI_BIN                                (void *)(resource_root + 0x00227238)
#define   SIRI_0_BIN                              (void *)(resource_root + 0x0022a1f8)
#define   SIRI_1_BIN                              (void *)(resource_root + 0x0022d438)
#define   SIRI_10_BIN                             (void *)(resource_root + 0x00230678)
#define   SIRI_11_BIN                             (void *)(resource_root + 0x002338b8)
#define   SIRI_12_BIN                             (void *)(resource_root + 0x00236af8)
#define   SIRI_13_BIN                             (void *)(resource_root + 0x00239d38)
#define   SIRI_14_BIN                             (void *)(resource_root + 0x0023cf78)
#define   SIRI_15_BIN                             (void *)(resource_root + 0x002401b8)
#define   SIRI_16_BIN                             (void *)(resource_root + 0x002433f8)
#define   SIRI_17_BIN                             (void *)(resource_root + 0x00246638)
#define   SIRI_18_BIN                             (void *)(resource_root + 0x00249878)
#define   SIRI_19_BIN                             (void *)(resource_root + 0x0024cab8)
#define   SIRI_2_BIN                              (void *)(resource_root + 0x0024e6f8)
#define   SIRI_21_BIN                             (void *)(resource_root + 0x00251938)
#define   SIRI_3_BIN                              (void *)(resource_root + 0x00253578)
#define   SIRI_4_BIN                              (void *)(resource_root + 0x002567b8)
#define   SIRI_5_BIN                              (void *)(resource_root + 0x002599f8)
#define   SIRI_6_BIN                              (void *)(resource_root + 0x0025cc38)
#define   SIRI_7_BIN                              (void *)(resource_root + 0x0025fe78)
#define   SIRI_70_70_BIN                          (void *)(resource_root + 0x002630b8)
#define   SIRI_8_BIN                              (void *)(resource_root + 0x00266078)
#define   SIRI_80_80_BIN                          (void *)(resource_root + 0x002692b8)
#define   SIRI_9_BIN                              (void *)(resource_root + 0x0026c4f8)
#define   SKY0_BIN                                (void *)(resource_root + 0x0026f738)
#define   SKY1_BIN                                (void *)(resource_root + 0x002703f8)
#define   SOUND_BIN                               (void *)(resource_root + 0x002710b8)
#define   SOUND_RECORDING_BIN                     (void *)(resource_root + 0x00276078)
#define   SOUND_RECORDING_0_BIN                   (void *)(resource_root + 0x00276d38)
#define   SPORT_BIN                               (void *)(resource_root + 0x002785f8)
#define   SPORT_0_BIN                             (void *)(resource_root + 0x00279338)
#define   TEXT_0_BIN                              (void *)(resource_root + 0x0027abf8)
#define   TEXT_1_BIN                              (void *)(resource_root + 0x0027bcb8)
#define   TEXT_2_BIN                              (void *)(resource_root + 0x0027e578)
#define   TIME_BIN                                (void *)(resource_root + 0x0027eff8)
#define   WAVE_BIN                                (void *)(resource_root + 0x00280e38)
#define   WEIXIN_BIN                              (void *)(resource_root + 0x00281838)
#define   CLOCKN_BIN                              (void *)(resource_root + 0x002830f8)
#define   HEARTRATE_BIN                           (void *)(resource_root + 0x00324138)
#define   MUSIC_BIN                               (void *)(resource_root + 0x003c5178)
#define   QUICKCARD_BIN                           (void *)(resource_root + 0x004661b8)
#define   WEATHER_BIN                             (void *)(resource_root + 0x005071f8)
#define   ALARM_CLOCK_OFF_BIN                     (void *)(resource_root + 0x005a8238)
#define   ALARM_CLOCK_ON_BIN                      (void *)(resource_root + 0x005b8538)
#define   DOG100_BIN                              (void *)(resource_root + 0x005c8978)
#define   DOG120_BIN                              (void *)(resource_root + 0x005de778)
#define   DOG140_BIN                              (void *)(resource_root + 0x005f4578)
#define   DOG160_BIN                              (void *)(resource_root + 0x0060a378)
#define   DOG180_BIN                              (void *)(resource_root + 0x00620178)
#define   DOG20_BIN                               (void *)(resource_root + 0x00635f78)
#define   DOG200_BIN                              (void *)(resource_root + 0x0064bd78)
#define   DOG220_BIN                              (void *)(resource_root + 0x00661b78)
#define   DOG240_BIN                              (void *)(resource_root + 0x00677978)
#define   DOG260_BIN                              (void *)(resource_root + 0x0068d778)
#define   DOG280_BIN                              (void *)(resource_root + 0x006a3578)
#define   DOG300_BIN                              (void *)(resource_root + 0x006b9378)
#define   DOG320_BIN                              (void *)(resource_root + 0x006cf178)
#define   DOG340_BIN                              (void *)(resource_root + 0x006e4f78)
#define   DOG360_BIN                              (void *)(resource_root + 0x006fad78)
#define   DOG40_BIN                               (void *)(resource_root + 0x00710b78)
#define   DOG60_BIN                               (void *)(resource_root + 0x00726978)
#define   DOG80_BIN                               (void *)(resource_root + 0x0073c778)
#define   BEIJIN_BIN                              (void *)(resource_root + 0x00752578)
#define   BRIGHT_OFF_BIN                          (void *)(resource_root + 0x00764538)
#define   BRIGHT_ON_BIN                           (void *)(resource_root + 0x00774838)
#define   BUTTON_CAL_BLK_BIN                      (void *)(resource_root + 0x00784b38)
#define   BUTTON_CAL_BLK_LONG_BIN                 (void *)(resource_root + 0x00787438)
#define   BUTTON_CAL_DEL_BIN                      (void *)(resource_root + 0x0078c838)
#define   BUTTON_CAL_GRAY_BIN                     (void *)(resource_root + 0x0078cf78)
#define   BUTTON_CAL_GRAY_LONG_BIN                (void *)(resource_root + 0x0078f878)
#define   BUTTON_CAL_ORG_BIN                      (void *)(resource_root + 0x00794c78)
#define   BUTTON_CAL_YELLOW_BIN                   (void *)(resource_root + 0x00797578)
#define   CALL_OFF_BIN                            (void *)(resource_root + 0x00799e78)
#define   CALL_ON_BIN                             (void *)(resource_root + 0x007aa178)
#define   CARD_HEALTH_BIN                         (void *)(resource_root + 0x007ba4b8)
#define   CARD_MORE_BIN                           (void *)(resource_root + 0x007e37b8)
#define   CARD_MUSIC_BIN                          (void *)(resource_root + 0x0080cab8)
#define   CARD_MUSIC1_BIN                         (void *)(resource_root + 0x00835db8)
#define   CARD_WEATHER1_BIN                       (void *)(resource_root + 0x0085f0b8)
#define   DIANHUAGUAN_BIN                         (void *)(resource_root + 0x008883b8)
#define   DIANHUAKAI_BIN                          (void *)(resource_root + 0x0089a378)
#define   FLASHLIGHT_OFF_BIN                      (void *)(resource_root + 0x008ac338)
#define   FLASHLIGHT_ON_BIN                       (void *)(resource_root + 0x008bc638)
#define   GBK_32_32_DOT_BIN                       (void *)(resource_root + 0x008cc978)
#define   GBK_UNICODE_TABLE_BIN                   (void *)(resource_root + 0x00be6bb8)
#define   FONT_RAR                                (void *)(resource_root + 0x00c06bf8)
#define   PULL_UP_ALL_APP_ICON_BIN                (void *)(resource_root + 0x00d1fcf8)
#define   PULL_UP_BATTERY_LEVEL_BG_BIN            (void *)(resource_root + 0x00d204b8)
#define   PULL_UP_BATTERY_LEVEL_CHARGE_BIN        (void *)(resource_root + 0x00d21078)
#define   PULL_UP_BATTERY_LEVEL_NUM_0_BIN         (void *)(resource_root + 0x00d21338)
#define   PULL_UP_BATTERY_LEVEL_NUM_1_BIN         (void *)(resource_root + 0x00d218b8)
#define   PULL_UP_BATTERY_LEVEL_NUM_2_BIN         (void *)(resource_root + 0x00d21d38)
#define   PULL_UP_BATTERY_LEVEL_NUM_3_BIN         (void *)(resource_root + 0x00d222b8)
#define   PULL_UP_BATTERY_LEVEL_NUM_4_BIN         (void *)(resource_root + 0x00d22878)
#define   PULL_UP_BATTERY_LEVEL_NUM_5_BIN         (void *)(resource_root + 0x00d22cf8)
#define   PULL_UP_BATTERY_LEVEL_NUM_6_BIN         (void *)(resource_root + 0x00d232f8)
#define   PULL_UP_BATTERY_LEVEL_NUM_7_BIN         (void *)(resource_root + 0x00d23938)
#define   PULL_UP_BATTERY_LEVEL_NUM_8_BIN         (void *)(resource_root + 0x00d23df8)
#define   PULL_UP_BATTERY_LEVEL_NUM_9_BIN         (void *)(resource_root + 0x00d244f8)
#define   PULL_UP_BATTERY_LEVEL_NUM_PER_BIN       (void *)(resource_root + 0x00d24af8)
#define   PULL_UP_BATTERY_LEVEL_PROGRESS_100_BIN  (void *)(resource_root + 0x00d252f8)
#define   PULL_UP_BATTERY_LEVEL_PROGRESS_20_BIN   (void *)(resource_root + 0x00d26fb8)
#define   PULL_UP_BATTERY_LEVEL_PROGRESS_40_BIN   (void *)(resource_root + 0x00d28cf8)
#define   PULL_UP_BATTERY_LEVEL_PROGRESS_60_BIN   (void *)(resource_root + 0x00d2abf8)
#define   PULL_UP_BATTERY_LEVEL_PROGRESS_80_BIN   (void *)(resource_root + 0x00d2cb38)
#define   PULL_UP_BATTERY_LEVEL_PROGRESS_LOW_BIN  (void *)(resource_root + 0x00d2e878)
#define   PULL_UP_BO_ICON_BIN                     (void *)(resource_root + 0x00d305b8)
#define   PULL_UP_BO_NUM_0_BIN                    (void *)(resource_root + 0x00d31df8)
#define   PULL_UP_BO_NUM_1_BIN                    (void *)(resource_root + 0x00d32338)
#define   PULL_UP_BO_NUM_2_BIN                    (void *)(resource_root + 0x00d32778)
#define   PULL_UP_BO_NUM_3_BIN                    (void *)(resource_root + 0x00d32bf8)
#define   PULL_UP_BO_NUM_4_BIN                    (void *)(resource_root + 0x00d330f8)
#define   PULL_UP_BO_NUM_5_BIN                    (void *)(resource_root + 0x00d33478)
#define   PULL_UP_BO_NUM_6_BIN                    (void *)(resource_root + 0x00d33938)
#define   PULL_UP_BO_NUM_7_BIN                    (void *)(resource_root + 0x00d33e38)
#define   PULL_UP_BO_NUM_8_BIN                    (void *)(resource_root + 0x00d34238)
#define   PULL_UP_BO_NUM_9_BIN                    (void *)(resource_root + 0x00d347b8)
#define   PULL_UP_BO_NUM_PER_BIN                  (void *)(resource_root + 0x00d34cf8)
#define   PULL_UP_BO_UNIT_CH_BIN                  (void *)(resource_root + 0x00d35438)
#define   PULL_UP_BO_UNIT_EN_BIN                  (void *)(resource_root + 0x00d367f8)
#define   PULL_UP_BP_ICON_BIN                     (void *)(resource_root + 0x00d37338)
#define   PULL_UP_BP_NUM_0_BIN                    (void *)(resource_root + 0x00d381b8)
#define   PULL_UP_BP_NUM_1_BIN                    (void *)(resource_root + 0x00d386f8)
#define   PULL_UP_BP_NUM_2_BIN                    (void *)(resource_root + 0x00d38b38)
#define   PULL_UP_BP_NUM_3_BIN                    (void *)(resource_root + 0x00d38fb8)
#define   PULL_UP_BP_NUM_4_BIN                    (void *)(resource_root + 0x00d394b8)
#define   PULL_UP_BP_NUM_5_BIN                    (void *)(resource_root + 0x00d39838)
#define   PULL_UP_BP_NUM_6_BIN                    (void *)(resource_root + 0x00d39cf8)
#define   PULL_UP_BP_NUM_7_BIN                    (void *)(resource_root + 0x00d3a1f8)
#define   PULL_UP_BP_NUM_8_BIN                    (void *)(resource_root + 0x00d3a5f8)
#define   PULL_UP_BP_NUM_9_BIN                    (void *)(resource_root + 0x00d3ab78)
#define   PULL_UP_BP_NUM_SLASH_BIN                (void *)(resource_root + 0x00d3b0b8)
#define   PULL_UP_BP_UNIT_CH_BIN                  (void *)(resource_root + 0x00d3b478)
#define   PULL_UP_BP_UNIT_EN_BIN                  (void *)(resource_root + 0x00d3c178)
#define   PULL_UP_CLOCK_BG_BIN                    (void *)(resource_root + 0x00d3ceb8)
#define   PULL_UP_CLOCK_CIRCLE_BIN                (void *)(resource_root + 0x00d40278)
#define   PULL_UP_CLOCK_DATE_0_BIN                (void *)(resource_root + 0x00d40438)
#define   PULL_UP_CLOCK_DATE_1_BIN                (void *)(resource_root + 0x00d408f8)
#define   PULL_UP_CLOCK_DATE_2_BIN                (void *)(resource_root + 0x00d40bf8)
#define   PULL_UP_CLOCK_DATE_3_BIN                (void *)(resource_root + 0x00d41078)
#define   PULL_UP_CLOCK_DATE_4_BIN                (void *)(resource_root + 0x00d41578)
#define   PULL_UP_CLOCK_DATE_5_BIN                (void *)(resource_root + 0x00d41938)
#define   PULL_UP_CLOCK_DATE_6_BIN                (void *)(resource_root + 0x00d41e38)
#define   PULL_UP_CLOCK_DATE_7_BIN                (void *)(resource_root + 0x00d42378)
#define   PULL_UP_CLOCK_DATE_8_BIN                (void *)(resource_root + 0x00d42778)
#define   PULL_UP_CLOCK_DATE_9_BIN                (void *)(resource_root + 0x00d42d78)
#define   PULL_UP_CLOCK_DATE_LINE_BIN             (void *)(resource_root + 0x00d43278)
#define   PULL_UP_CLOCK_HOUR_BIN                  (void *)(resource_root + 0x00d433f8)
#define   PULL_UP_CLOCK_MINUTE_BIN                (void *)(resource_root + 0x00d439f8)
#define   PULL_UP_CLOCK_SECOND_BIN                (void *)(resource_root + 0x00d442f8)
#define   PULL_UP_CLOCK_WEEK_CH_1_BIN             (void *)(resource_root + 0x00d445f8)
#define   PULL_UP_CLOCK_WEEK_CH_2_BIN             (void *)(resource_root + 0x00d44e38)
#define   PULL_UP_CLOCK_WEEK_CH_3_BIN             (void *)(resource_root + 0x00d45678)
#define   PULL_UP_CLOCK_WEEK_CH_4_BIN             (void *)(resource_root + 0x00d45f38)
#define   PULL_UP_CLOCK_WEEK_CH_5_BIN             (void *)(resource_root + 0x00d46c38)
#define   PULL_UP_CLOCK_WEEK_CH_6_BIN             (void *)(resource_root + 0x00d476f8)
#define   PULL_UP_CLOCK_WEEK_CH_7_BIN             (void *)(resource_root + 0x00d48278)
#define   PULL_UP_CLOCK_WEEK_EN_1_BIN             (void *)(resource_root + 0x00d48cf8)
#define   PULL_UP_CLOCK_WEEK_EN_2_BIN             (void *)(resource_root + 0x00d49c78)
#define   PULL_UP_CLOCK_WEEK_EN_3_BIN             (void *)(resource_root + 0x00d4a5f8)
#define   PULL_UP_CLOCK_WEEK_EN_4_BIN             (void *)(resource_root + 0x00d4b278)
#define   PULL_UP_CLOCK_WEEK_EN_5_BIN             (void *)(resource_root + 0x00d4bd38)
#define   PULL_UP_CLOCK_WEEK_EN_6_BIN             (void *)(resource_root + 0x00d4c538)
#define   PULL_UP_CLOCK_WEEK_EN_7_BIN             (void *)(resource_root + 0x00d4d038)
#define   PULL_UP_COMPASS_BG_BIN                  (void *)(resource_root + 0x00d4df78)
#define   PULL_UP_COMPASS_DIRECTION_ARROW_BIN     (void *)(resource_root + 0x00d4ee38)
#define   PULL_UP_COMPASS_NUM_0_BIN               (void *)(resource_root + 0x00d53f78)
#define   PULL_UP_COMPASS_NUM_1_BIN               (void *)(resource_root + 0x00d54538)
#define   PULL_UP_COMPASS_NUM_2_BIN               (void *)(resource_root + 0x00d548f8)
#define   PULL_UP_COMPASS_NUM_3_BIN               (void *)(resource_root + 0x00d54eb8)
#define   PULL_UP_COMPASS_NUM_4_BIN               (void *)(resource_root + 0x00d554b8)
#define   PULL_UP_COMPASS_NUM_5_BIN               (void *)(resource_root + 0x00d55978)
#define   PULL_UP_COMPASS_NUM_6_BIN               (void *)(resource_root + 0x00d55f78)
#define   PULL_UP_COMPASS_NUM_7_BIN               (void *)(resource_root + 0x00d565f8)
#define   PULL_UP_COMPASS_NUM_8_BIN               (void *)(resource_root + 0x00d56af8)
#define   PULL_UP_COMPASS_NUM_9_BIN               (void *)(resource_root + 0x00d57238)
#define   PULL_UP_COMPASS_NUM_DEGREE_BIN          (void *)(resource_root + 0x00d57878)
#define   PULL_UP_COMPASS_NUM_TILDE_BIN           (void *)(resource_root + 0x00d57bf8)
#define   PULL_UP_COMPASS_UNIT_CH_E_BIN           (void *)(resource_root + 0x00d57eb8)
#define   PULL_UP_COMPASS_UNIT_CH_N_BIN           (void *)(resource_root + 0x00d587b8)
#define   PULL_UP_COMPASS_UNIT_CH_NE_BIN          (void *)(resource_root + 0x00d59238)
#define   PULL_UP_COMPASS_UNIT_CH_NW_BIN          (void *)(resource_root + 0x00d5a0f8)
#define   PULL_UP_COMPASS_UNIT_CH_S_BIN           (void *)(resource_root + 0x00d5af78)
#define   PULL_UP_COMPASS_UNIT_CH_SE_BIN          (void *)(resource_root + 0x00d5b8b8)
#define   PULL_UP_COMPASS_UNIT_CH_SW_BIN          (void *)(resource_root + 0x00d5c6b8)
#define   PULL_UP_COMPASS_UNIT_CH_W_BIN           (void *)(resource_root + 0x00d5d438)
#define   PULL_UP_COMPASS_UNIT_EN_E_BIN           (void *)(resource_root + 0x00d5dcb8)
#define   PULL_UP_COMPASS_UNIT_EN_N_BIN           (void *)(resource_root + 0x00d5e178)
#define   PULL_UP_COMPASS_UNIT_EN_NE_BIN          (void *)(resource_root + 0x00d5e878)
#define   PULL_UP_COMPASS_UNIT_EN_NW_BIN          (void *)(resource_root + 0x00d5f278)
#define   PULL_UP_COMPASS_UNIT_EN_S_BIN           (void *)(resource_root + 0x00d601f8)
#define   PULL_UP_COMPASS_UNIT_EN_SE_BIN          (void *)(resource_root + 0x00d608f8)
#define   PULL_UP_COMPASS_UNIT_EN_SW_BIN          (void *)(resource_root + 0x00d61278)
#define   PULL_UP_COMPASS_UNIT_EN_W_BIN           (void *)(resource_root + 0x00d62178)
#define   PULL_UP_HEART_BG_BIN                    (void *)(resource_root + 0x00d62c78)
#define   PULL_UP_HEART_UNIT_CH_BIN               (void *)(resource_root + 0x00d73f78)
#define   PULL_UP_HEART_UNIT_EN_BIN               (void *)(resource_root + 0x00d74878)
#define   PULL_UP_MUSIC_BACK_BIN                  (void *)(resource_root + 0x00d75178)
#define   PULL_UP_MUSIC_BACK_PRESS_BIN            (void *)(resource_root + 0x00d756f8)
#define   PULL_UP_MUSIC_BG_BIN                    (void *)(resource_root + 0x00d75c78)
#define   PULL_UP_MUSIC_FORWARD_BIN               (void *)(resource_root + 0x00d81f38)
#define   PULL_UP_MUSIC_FORWARD_PRESS_BIN         (void *)(resource_root + 0x00d824b8)
#define   PULL_UP_MUSIC_START_BIN                 (void *)(resource_root + 0x00d82a38)
#define   PULL_UP_MUSIC_START_PRESS_BIN           (void *)(resource_root + 0x00d854b8)
#define   PULL_UP_NAVIGATION_BG_BIN               (void *)(resource_root + 0x00d87eb8)
#define   PULL_UP_BG_BIN                          (void *)(resource_root + 0x00db3d38)
#define   CALENDAR_BIN                            (void *)(resource_root + 0x00db6278)
#define   RECENT_APP_ALIPAY_BIN                   (void *)(resource_root + 0x00db8ab8)
#define   RECENT_APP_APP_CENTER_BIN               (void *)(resource_root + 0x00dbb5f8)
#define   RECENT_APP_BO_BIN                       (void *)(resource_root + 0x00dbd578)
#define   RECENT_APP_BP_BIN                       (void *)(resource_root + 0x00dc0378)
#define   RECENT_APP_BREATHE_BIN                  (void *)(resource_root + 0x00dc24b8)
#define   RECENT_APP_BRIGHT_SCREEN_BIN            (void *)(resource_root + 0x00dc7c38)
#define   RECENT_APP_BS_BIN                       (void *)(resource_root + 0x00dc9db8)
#define   RECENT_APP_CAL_BIN                      (void *)(resource_root + 0x00dcc2f8)
#define   RECENT_APP_CAMERA_BIN                   (void *)(resource_root + 0x00dd2038)
#define   RECENT_APP_CLOCK_BIN                    (void *)(resource_root + 0x00dd4c78)
#define   RECENT_APP_COMPASS_BIN                  (void *)(resource_root + 0x00dd7b38)
#define   RECENT_APP_DIAL_BIN                     (void *)(resource_root + 0x00dd9938)
#define   RECENT_APP_FIND_BIN                     (void *)(resource_root + 0x00ddac78)
#define   RECENT_APP_GAME_BIN                     (void *)(resource_root + 0x00dddf38)
#define   RECENT_APP_HR_BIN                       (void *)(resource_root + 0x00de0e38)
#define   RECENT_APP_MAP_BIN                      (void *)(resource_root + 0x00de5f38)
#define   RECENT_APP_MET_BIN                      (void *)(resource_root + 0x00de94b8)
#define   RECENT_APP_MSG_BIN                      (void *)(resource_root + 0x00deb778)
#define   RECENT_APP_MUSIC_BIN                    (void *)(resource_root + 0x00defef8)
#define   RECENT_APP_PRESSURE_BIN                 (void *)(resource_root + 0x00df56f8)
#define   RECENT_APP_QQ_BIN                       (void *)(resource_root + 0x00dfba78)
#define   RECENT_APP_QR_BIN                       (void *)(resource_root + 0x00dfcfb8)
#define   RECENT_APP_RECORD_BIN                   (void *)(resource_root + 0x00dff1b8)
#define   RECENT_APP_SETTING_BIN                  (void *)(resource_root + 0x00e02038)
#define   RECENT_APP_SIRI_BIN                     (void *)(resource_root + 0x00e06478)
#define   RECENT_APP_SLEEP_BIN                    (void *)(resource_root + 0x00e0d378)
#define   RECENT_APP_SPORT_BIN                    (void *)(resource_root + 0x00e10b78)
#define   RECENT_APP_STEP_BIN                     (void *)(resource_root + 0x00e135b8)
#define   RECENT_APP_STOCK_MARKET_BIN             (void *)(resource_root + 0x00e187f8)
#define   RECENT_APP_TEL_BIN                      (void *)(resource_root + 0x00e1c478)
#define   RECENT_APP_TEMPERATURE_BIN              (void *)(resource_root + 0x00e21f38)
#define   RECENT_APP_THEME_BIN                    (void *)(resource_root + 0x00e24c38)
#define   RECENT_APP_TIMER_BIN                    (void *)(resource_root + 0x00e27178)
#define   RECENT_APP_TRAJECTORY_BIN               (void *)(resource_root + 0x00e29ff8)
#define   RECENT_APP_WEATHER_BIN                  (void *)(resource_root + 0x00e2cb38)
#define   RECENT_APP_WEATHER_PRESSURE_BIN         (void *)(resource_root + 0x00e2f5f8)
#define   RECENT_APP_WOMAN_BIN                    (void *)(resource_root + 0x00e351f8)
#define   PULL_UP_STEP_CAL_NUM_0_BIN              (void *)(resource_root + 0x00e37178)
#define   PULL_UP_STEP_CAL_NUM_1_BIN              (void *)(resource_root + 0x00e375f8)
#define   PULL_UP_STEP_CAL_NUM_2_BIN              (void *)(resource_root + 0x00e379b8)
#define   PULL_UP_STEP_CAL_NUM_3_BIN              (void *)(resource_root + 0x00e37db8)
#define   PULL_UP_STEP_CAL_NUM_4_BIN              (void *)(resource_root + 0x00e38278)
#define   PULL_UP_STEP_CAL_NUM_5_BIN              (void *)(resource_root + 0x00e38678)
#define   PULL_UP_STEP_CAL_NUM_6_BIN              (void *)(resource_root + 0x00e38b38)
#define   PULL_UP_STEP_CAL_NUM_7_BIN              (void *)(resource_root + 0x00e38ff8)
#define   PULL_UP_STEP_CAL_NUM_8_BIN              (void *)(resource_root + 0x00e39378)
#define   PULL_UP_STEP_CAL_NUM_9_BIN              (void *)(resource_root + 0x00e398b8)
#define   PULL_UP_STEP_DIS_NUM_0_BIN              (void *)(resource_root + 0x00e39d78)
#define   PULL_UP_STEP_DIS_NUM_1_BIN              (void *)(resource_root + 0x00e3a1f8)
#define   PULL_UP_STEP_DIS_NUM_2_BIN              (void *)(resource_root + 0x00e3a5b8)
#define   PULL_UP_STEP_DIS_NUM_3_BIN              (void *)(resource_root + 0x00e3a9b8)
#define   PULL_UP_STEP_DIS_NUM_4_BIN              (void *)(resource_root + 0x00e3ae78)
#define   PULL_UP_STEP_DIS_NUM_5_BIN              (void *)(resource_root + 0x00e3b278)
#define   PULL_UP_STEP_DIS_NUM_6_BIN              (void *)(resource_root + 0x00e3b738)
#define   PULL_UP_STEP_DIS_NUM_7_BIN              (void *)(resource_root + 0x00e3bbf8)
#define   PULL_UP_STEP_DIS_NUM_8_BIN              (void *)(resource_root + 0x00e3bf78)
#define   PULL_UP_STEP_DIS_NUM_9_BIN              (void *)(resource_root + 0x00e3c4b8)
#define   PULL_UP_STEP_DIS_NUM_DOT_BIN            (void *)(resource_root + 0x00e3c978)
#define   PULL_UP_STEP_ICON_BIN                   (void *)(resource_root + 0x00e3caf8)
#define   PULL_UP_STEP_STEPS_NUM_0_BIN            (void *)(resource_root + 0x00e3f7f8)
#define   PULL_UP_STEP_STEPS_NUM_1_BIN            (void *)(resource_root + 0x00e3fc78)
#define   PULL_UP_STEP_STEPS_NUM_2_BIN            (void *)(resource_root + 0x00e40038)
#define   PULL_UP_STEP_STEPS_NUM_3_BIN            (void *)(resource_root + 0x00e40438)
#define   PULL_UP_STEP_STEPS_NUM_4_BIN            (void *)(resource_root + 0x00e408f8)
#define   PULL_UP_STEP_STEPS_NUM_5_BIN            (void *)(resource_root + 0x00e40cf8)
#define   PULL_UP_STEP_STEPS_NUM_6_BIN            (void *)(resource_root + 0x00e411b8)
#define   PULL_UP_STEP_STEPS_NUM_7_BIN            (void *)(resource_root + 0x00e41678)
#define   PULL_UP_STEP_STEPS_NUM_8_BIN            (void *)(resource_root + 0x00e419f8)
#define   PULL_UP_STEP_STEPS_NUM_9_BIN            (void *)(resource_root + 0x00e41f38)
#define   PULL_UP_WEATHER_BG_BIN                  (void *)(resource_root + 0x00e424f8)
#define   PULL_UP_WEATHER_CLOUDY_BIN              (void *)(resource_root + 0x00e430b8)
#define   PULL_UP_WEATHER_NUM_0_BIN               (void *)(resource_root + 0x00e43e38)
#define   PULL_UP_WEATHER_NUM_1_BIN               (void *)(resource_root + 0x00e442f8)
#define   PULL_UP_WEATHER_NUM_2_BIN               (void *)(resource_root + 0x00e445f8)
#define   PULL_UP_WEATHER_NUM_3_BIN               (void *)(resource_root + 0x00e44a78)
#define   PULL_UP_WEATHER_NUM_4_BIN               (void *)(resource_root + 0x00e44f78)
#define   PULL_UP_WEATHER_NUM_5_BIN               (void *)(resource_root + 0x00e45338)
#define   PULL_UP_WEATHER_NUM_6_BIN               (void *)(resource_root + 0x00e45838)
#define   PULL_UP_WEATHER_NUM_7_BIN               (void *)(resource_root + 0x00e45d78)
#define   PULL_UP_WEATHER_NUM_8_BIN               (void *)(resource_root + 0x00e46178)
#define   PULL_UP_WEATHER_NUM_9_BIN               (void *)(resource_root + 0x00e46778)
#define   PULL_UP_WEATHER_NUM_C_BIN               (void *)(resource_root + 0x00e46c78)
#define   PULL_UP_WEATHER_NUM_F_BIN               (void *)(resource_root + 0x00e47238)
#define   PULL_UP_WEATHER_NUM_LINE_BIN            (void *)(resource_root + 0x00e47678)
#define   PULL_UP_WEATHER_RAIN_BIN                (void *)(resource_root + 0x00e477f8)
#define   PULL_UP_WEATHER_SNOW_BIN                (void *)(resource_root + 0x00e483b8)
#define   PULL_UP_WEATHER_SUNNY_BIN               (void *)(resource_root + 0x00e48ef8)
#define   PULL_UP_WEATHER_UNKNOWN_BIN             (void *)(resource_root + 0x00e4b038)
#define   JINGYINGUAN_BIN                         (void *)(resource_root + 0x00e4b8f8)
#define   JINGYINKAI_BIN                          (void *)(resource_root + 0x00e5d8b8)
#define   JUYUANMOSHIGUAN_BIN                     (void *)(resource_root + 0x00e6f878)
#define   JUYUANMOSHIKAI_BIN                      (void *)(resource_root + 0x00e81838)
#define   LIANGDUGUAN_BIN                         (void *)(resource_root + 0x00e937f8)
#define   LIANGDUKAI_BIN                          (void *)(resource_root + 0x00ea57b8)
#define   LINGSHENGGUAN_BIN                       (void *)(resource_root + 0x00eb7778)
#define   LINGSHENGKAI_BIN                        (void *)(resource_root + 0x00ec9738)
#define   MUTE_OFF_BIN                            (void *)(resource_root + 0x00edb6f8)
#define   MUTE_ON_BIN                             (void *)(resource_root + 0x00eeb9f8)
#define   NAOZHONGGUAN_BIN                        (void *)(resource_root + 0x00efbcf8)
#define   NAOZHONGKAI_BIN                         (void *)(resource_root + 0x00f0dcb8)
#define   NO_DISTURB_OFF_BIN                      (void *)(resource_root + 0x00f1fc78)
#define   NO_DISTURB_ON_BIN                       (void *)(resource_root + 0x00f2ff78)
#define   RECT_221_269_BIN                        (void *)(resource_root + 0x00f40278)
#define   RING_OFF_BIN                            (void *)(resource_root + 0x00f7a378)
#define   RING_ON_BIN                             (void *)(resource_root + 0x00f8a678)
#define   SET_OFF_BIN                             (void *)(resource_root + 0x00f9a978)
#define   SET_ON_BIN                              (void *)(resource_root + 0x00faac78)
#define   SHEZHIGUAN_BIN                          (void *)(resource_root + 0x00fbaf78)
#define   SHEZHIKAI_BIN                           (void *)(resource_root + 0x00fccf38)
#define   SHIZHONGGUAN_BIN                        (void *)(resource_root + 0x00fdeef8)
#define   SHIZHONGKAI_BIN                         (void *)(resource_root + 0x00ff0eb8)
#define   SHOUDIANTONGGUAN_BIN                    (void *)(resource_root + 0x01002e78)
#define   SHOUDIANTONGKAI_BIN                     (void *)(resource_root + 0x01014e38)
#define   SIGNAL_OFF_BIN                          (void *)(resource_root + 0x01026df8)
#define   SIGNAL_ON_BIN                           (void *)(resource_root + 0x010370f8)
#define   SIMKAI_SIZE24_BITS4_FONT_BIN            (void *)(resource_root + 0x010473f8)
#define   THEATRE_OFF_BIN                         (void *)(resource_root + 0x01060738)
#define   THEATRE_ON_BIN                          (void *)(resource_root + 0x01070a38)
#define   VIBRATE_OFF_BIN                         (void *)(resource_root + 0x01080d38)
#define   VIBRATE_ON_BIN                          (void *)(resource_root + 0x01091038)
#define   WATCH_OFF_BIN                           (void *)(resource_root + 0x010a1338)
#define   WATCH_ON_BIN                            (void *)(resource_root + 0x010b1638)
#define   WURAOGUAN_BIN                           (void *)(resource_root + 0x010c1938)
#define   WURAOKAI_BIN                            (void *)(resource_root + 0x010d38f8)
#define   XINHAOGUAN_BIN                          (void *)(resource_root + 0x010e58b8)
#define   XINHAOKAI_BIN                           (void *)(resource_root + 0x010f7878)
#define   ZHENDONGGUAN_BIN                        (void *)(resource_root + 0x01109838)
#define   ZHENDONGKAI_BIN                         (void *)(resource_root + 0x0111b7f8)

#else
#define   ACTIVITY_BIN                            (void *)(0x0c0004b8)
#define   APP_LIST3_BIN                           (void *)(0x0c0a19f8)
#define   CURTAIN_RECT_248_385_BIN                (void *)(0x0c0a2cf8)
#define   SAT_BIN                                 (void *)(0x0c0d16f8)
#define   SUN_BIN                                 (void *)(0x0c0d2578)
#define   THU_BIN                                 (void *)(0x0c0d33f8)
#define   TUE_BIN                                 (void *)(0x0c0d4278)
#define   WED_BIN                                 (void *)(0x0c0d50f8)
#define   WHATSAPP_BIN                            (void *)(0x0c0d5f78)
#define   ADD_BIN                                 (void *)(0x0c0d7838)
#define   ASSEMBLY_BIN                            (void *)(0x0c0d7b78)
#define   AUDIO_FREQUENCY_BIN                     (void *)(0x0c0d7bf8)
#define   CALLING_0_BIN                           (void *)(0x0c0dcbb8)
#define   CENTIGRADE_BIN                          (void *)(0x0c0de738)
#define   CIRCLE_BIN                              (void *)(0x0c0ded78)
#define   CLOSE_BIN                               (void *)(0x0c0e0638)
#define   DATA_BIN                                (void *)(0x0c0e8f38)
#define   DELETE_BIN                              (void *)(0x0c0e9a78)
#define   DIRECTION_BIN                           (void *)(0x0c0ea938)
#define   FACEBOOK_BIN                            (void *)(0x0c0eb538)
#define   FRI_BIN                                 (void *)(0x0c0eceb8)
#define   HEART_RATE_BIN                          (void *)(0x0c0edd38)
#define   INSTAGRAM_BIN                           (void *)(0x0c0ee9f8)
#define   LNE_BIN                                 (void *)(0x0c0f02b8)
#define   MAP_BIN                                 (void *)(0x0c0f1b78)
#define   MESSAGE_0_BIN                           (void *)(0x0c0f7878)
#define   MESSAGE_1_BIN                           (void *)(0x0c0f9138)
#define   MESSAGE_2_BIN                           (void *)(0x0c0fa9f8)
#define   MESSAGE_3_BIN                           (void *)(0x0c0fc2b8)
#define   MESSAGE_APP1L_BIN                       (void *)(0x0c107e78)
#define   MESSAGE_MUS_BIN                         (void *)(0x0c11d978)
#define   MESSAGE_WEIXIN_BIN                      (void *)(0x0c129538)
#define   MON_BIN                                 (void *)(0x0c13edf8)
#define   MUSIC_0_BIN                             (void *)(0x0c13fc78)
#define   MUSIC_1_BIN                             (void *)(0x0c140a38)
#define   NOTIFY_BIN                              (void *)(0x0c1432f8)
#define   RECT_100_127_BIN                        (void *)(0x0c175d38)
#define   RECT_110_108_BIN                        (void *)(0x0c17c0b8)
#define   RECT_146_50_BIN                         (void *)(0x0c181db8)
#define   RECT_160_385_BIN                        (void *)(0x0c1856f8)
#define   RECT_228_64_BIN                         (void *)(0x0c1a3878)
#define   RECT_300_126_BIN                        (void *)(0x0c1aaab8)
#define   RECT_300_127_BIN                        (void *)(0x0c1bd238)
#define   RECT_300_80_BIN                         (void *)(0x0c1cfbf8)
#define   RECT_350_348_BIN                        (void *)(0x0c1db7b8)
#define   RING_BIN                                (void *)(0x0c226578)
#define   SIRI_BIN                                (void *)(0x0c227238)
#define   SIRI_0_BIN                              (void *)(0x0c22a1f8)
#define   SIRI_1_BIN                              (void *)(0x0c22d438)
#define   SIRI_10_BIN                             (void *)(0x0c230678)
#define   SIRI_11_BIN                             (void *)(0x0c2338b8)
#define   SIRI_12_BIN                             (void *)(0x0c236af8)
#define   SIRI_13_BIN                             (void *)(0x0c239d38)
#define   SIRI_14_BIN                             (void *)(0x0c23cf78)
#define   SIRI_15_BIN                             (void *)(0x0c2401b8)
#define   SIRI_16_BIN                             (void *)(0x0c2433f8)
#define   SIRI_17_BIN                             (void *)(0x0c246638)
#define   SIRI_18_BIN                             (void *)(0x0c249878)
#define   SIRI_19_BIN                             (void *)(0x0c24cab8)
#define   SIRI_2_BIN                              (void *)(0x0c24e6f8)
#define   SIRI_21_BIN                             (void *)(0x0c251938)
#define   SIRI_3_BIN                              (void *)(0x0c253578)
#define   SIRI_4_BIN                              (void *)(0x0c2567b8)
#define   SIRI_5_BIN                              (void *)(0x0c2599f8)
#define   SIRI_6_BIN                              (void *)(0x0c25cc38)
#define   SIRI_7_BIN                              (void *)(0x0c25fe78)
#define   SIRI_70_70_BIN                          (void *)(0x0c2630b8)
#define   SIRI_8_BIN                              (void *)(0x0c266078)
#define   SIRI_80_80_BIN                          (void *)(0x0c2692b8)
#define   SIRI_9_BIN                              (void *)(0x0c26c4f8)
#define   SKY0_BIN                                (void *)(0x0c26f738)
#define   SKY1_BIN                                (void *)(0x0c2703f8)
#define   SOUND_BIN                               (void *)(0x0c2710b8)
#define   SOUND_RECORDING_BIN                     (void *)(0x0c276078)
#define   SOUND_RECORDING_0_BIN                   (void *)(0x0c276d38)
#define   SPORT_BIN                               (void *)(0x0c2785f8)
#define   SPORT_0_BIN                             (void *)(0x0c279338)
#define   TEXT_0_BIN                              (void *)(0x0c27abf8)
#define   TEXT_1_BIN                              (void *)(0x0c27bcb8)
#define   TEXT_2_BIN                              (void *)(0x0c27e578)
#define   TIME_BIN                                (void *)(0x0c27eff8)
#define   WAVE_BIN                                (void *)(0x0c280e38)
#define   WEIXIN_BIN                              (void *)(0x0c281838)
#define   CLOCKN_BIN                              (void *)(0x0c2830f8)
#define   HEARTRATE_BIN                           (void *)(0x0c324138)
#define   MUSIC_BIN                               (void *)(0x0c3c5178)
#define   QUICKCARD_BIN                           (void *)(0x0c4661b8)
#define   WEATHER_BIN                             (void *)(0x0c5071f8)
#define   ALARM_CLOCK_OFF_BIN                     (void *)(0x0c5a8238)
#define   ALARM_CLOCK_ON_BIN                      (void *)(0x0c5b8538)
#define   DOG100_BIN                              (void *)(0x0c5c8978)
#define   DOG120_BIN                              (void *)(0x0c5de778)
#define   DOG140_BIN                              (void *)(0x0c5f4578)
#define   DOG160_BIN                              (void *)(0x0c60a378)
#define   DOG180_BIN                              (void *)(0x0c620178)
#define   DOG20_BIN                               (void *)(0x0c635f78)
#define   DOG200_BIN                              (void *)(0x0c64bd78)
#define   DOG220_BIN                              (void *)(0x0c661b78)
#define   DOG240_BIN                              (void *)(0x0c677978)
#define   DOG260_BIN                              (void *)(0x0c68d778)
#define   DOG280_BIN                              (void *)(0x0c6a3578)
#define   DOG300_BIN                              (void *)(0x0c6b9378)
#define   DOG320_BIN                              (void *)(0x0c6cf178)
#define   DOG340_BIN                              (void *)(0x0c6e4f78)
#define   DOG360_BIN                              (void *)(0x0c6fad78)
#define   DOG40_BIN                               (void *)(0x0c710b78)
#define   DOG60_BIN                               (void *)(0x0c726978)
#define   DOG80_BIN                               (void *)(0x0c73c778)
#define   BEIJIN_BIN                              (void *)(0x0c752578)
#define   BRIGHT_OFF_BIN                          (void *)(0x0c764538)
#define   BRIGHT_ON_BIN                           (void *)(0x0c774838)
#define   BUTTON_CAL_BLK_BIN                      (void *)(0x0c784b38)
#define   BUTTON_CAL_BLK_LONG_BIN                 (void *)(0x0c787438)
#define   BUTTON_CAL_DEL_BIN                      (void *)(0x0c78c838)
#define   BUTTON_CAL_GRAY_BIN                     (void *)(0x0c78cf78)
#define   BUTTON_CAL_GRAY_LONG_BIN                (void *)(0x0c78f878)
#define   BUTTON_CAL_ORG_BIN                      (void *)(0x0c794c78)
#define   BUTTON_CAL_YELLOW_BIN                   (void *)(0x0c797578)
#define   CALL_OFF_BIN                            (void *)(0x0c799e78)
#define   CALL_ON_BIN                             (void *)(0x0c7aa178)
#define   CARD_HEALTH_BIN                         (void *)(0x0c7ba4b8)
#define   CARD_MORE_BIN                           (void *)(0x0c7e37b8)
#define   CARD_MUSIC_BIN                          (void *)(0x0c80cab8)
#define   CARD_MUSIC1_BIN                         (void *)(0x0c835db8)
#define   CARD_WEATHER1_BIN                       (void *)(0x0c85f0b8)
#define   DIANHUAGUAN_BIN                         (void *)(0x0c8883b8)
#define   DIANHUAKAI_BIN                          (void *)(0x0c89a378)
#define   FLASHLIGHT_OFF_BIN                      (void *)(0x0c8ac338)
#define   FLASHLIGHT_ON_BIN                       (void *)(0x0c8bc638)
#define   GBK_32_32_DOT_BIN                       (void *)(0x0c8cc978)
#define   GBK_UNICODE_TABLE_BIN                   (void *)(0x0cbe6bb8)
#define   FONT_RAR                                (void *)(0x0cc06bf8)
#define   PULL_UP_ALL_APP_ICON_BIN                (void *)(0x0cd1fcf8)
#define   PULL_UP_BATTERY_LEVEL_BG_BIN            (void *)(0x0cd204b8)
#define   PULL_UP_BATTERY_LEVEL_CHARGE_BIN        (void *)(0x0cd21078)
#define   PULL_UP_BATTERY_LEVEL_NUM_0_BIN         (void *)(0x0cd21338)
#define   PULL_UP_BATTERY_LEVEL_NUM_1_BIN         (void *)(0x0cd218b8)
#define   PULL_UP_BATTERY_LEVEL_NUM_2_BIN         (void *)(0x0cd21d38)
#define   PULL_UP_BATTERY_LEVEL_NUM_3_BIN         (void *)(0x0cd222b8)
#define   PULL_UP_BATTERY_LEVEL_NUM_4_BIN         (void *)(0x0cd22878)
#define   PULL_UP_BATTERY_LEVEL_NUM_5_BIN         (void *)(0x0cd22cf8)
#define   PULL_UP_BATTERY_LEVEL_NUM_6_BIN         (void *)(0x0cd232f8)
#define   PULL_UP_BATTERY_LEVEL_NUM_7_BIN         (void *)(0x0cd23938)
#define   PULL_UP_BATTERY_LEVEL_NUM_8_BIN         (void *)(0x0cd23df8)
#define   PULL_UP_BATTERY_LEVEL_NUM_9_BIN         (void *)(0x0cd244f8)
#define   PULL_UP_BATTERY_LEVEL_NUM_PER_BIN       (void *)(0x0cd24af8)
#define   PULL_UP_BATTERY_LEVEL_PROGRESS_100_BIN  (void *)(0x0cd252f8)
#define   PULL_UP_BATTERY_LEVEL_PROGRESS_20_BIN   (void *)(0x0cd26fb8)
#define   PULL_UP_BATTERY_LEVEL_PROGRESS_40_BIN   (void *)(0x0cd28cf8)
#define   PULL_UP_BATTERY_LEVEL_PROGRESS_60_BIN   (void *)(0x0cd2abf8)
#define   PULL_UP_BATTERY_LEVEL_PROGRESS_80_BIN   (void *)(0x0cd2cb38)
#define   PULL_UP_BATTERY_LEVEL_PROGRESS_LOW_BIN  (void *)(0x0cd2e878)
#define   PULL_UP_BO_ICON_BIN                     (void *)(0x0cd305b8)
#define   PULL_UP_BO_NUM_0_BIN                    (void *)(0x0cd31df8)
#define   PULL_UP_BO_NUM_1_BIN                    (void *)(0x0cd32338)
#define   PULL_UP_BO_NUM_2_BIN                    (void *)(0x0cd32778)
#define   PULL_UP_BO_NUM_3_BIN                    (void *)(0x0cd32bf8)
#define   PULL_UP_BO_NUM_4_BIN                    (void *)(0x0cd330f8)
#define   PULL_UP_BO_NUM_5_BIN                    (void *)(0x0cd33478)
#define   PULL_UP_BO_NUM_6_BIN                    (void *)(0x0cd33938)
#define   PULL_UP_BO_NUM_7_BIN                    (void *)(0x0cd33e38)
#define   PULL_UP_BO_NUM_8_BIN                    (void *)(0x0cd34238)
#define   PULL_UP_BO_NUM_9_BIN                    (void *)(0x0cd347b8)
#define   PULL_UP_BO_NUM_PER_BIN                  (void *)(0x0cd34cf8)
#define   PULL_UP_BO_UNIT_CH_BIN                  (void *)(0x0cd35438)
#define   PULL_UP_BO_UNIT_EN_BIN                  (void *)(0x0cd367f8)
#define   PULL_UP_BP_ICON_BIN                     (void *)(0x0cd37338)
#define   PULL_UP_BP_NUM_0_BIN                    (void *)(0x0cd381b8)
#define   PULL_UP_BP_NUM_1_BIN                    (void *)(0x0cd386f8)
#define   PULL_UP_BP_NUM_2_BIN                    (void *)(0x0cd38b38)
#define   PULL_UP_BP_NUM_3_BIN                    (void *)(0x0cd38fb8)
#define   PULL_UP_BP_NUM_4_BIN                    (void *)(0x0cd394b8)
#define   PULL_UP_BP_NUM_5_BIN                    (void *)(0x0cd39838)
#define   PULL_UP_BP_NUM_6_BIN                    (void *)(0x0cd39cf8)
#define   PULL_UP_BP_NUM_7_BIN                    (void *)(0x0cd3a1f8)
#define   PULL_UP_BP_NUM_8_BIN                    (void *)(0x0cd3a5f8)
#define   PULL_UP_BP_NUM_9_BIN                    (void *)(0x0cd3ab78)
#define   PULL_UP_BP_NUM_SLASH_BIN                (void *)(0x0cd3b0b8)
#define   PULL_UP_BP_UNIT_CH_BIN                  (void *)(0x0cd3b478)
#define   PULL_UP_BP_UNIT_EN_BIN                  (void *)(0x0cd3c178)
#define   PULL_UP_CLOCK_BG_BIN                    (void *)(0x0cd3ceb8)
#define   PULL_UP_CLOCK_CIRCLE_BIN                (void *)(0x0cd40278)
#define   PULL_UP_CLOCK_DATE_0_BIN                (void *)(0x0cd40438)
#define   PULL_UP_CLOCK_DATE_1_BIN                (void *)(0x0cd408f8)
#define   PULL_UP_CLOCK_DATE_2_BIN                (void *)(0x0cd40bf8)
#define   PULL_UP_CLOCK_DATE_3_BIN                (void *)(0x0cd41078)
#define   PULL_UP_CLOCK_DATE_4_BIN                (void *)(0x0cd41578)
#define   PULL_UP_CLOCK_DATE_5_BIN                (void *)(0x0cd41938)
#define   PULL_UP_CLOCK_DATE_6_BIN                (void *)(0x0cd41e38)
#define   PULL_UP_CLOCK_DATE_7_BIN                (void *)(0x0cd42378)
#define   PULL_UP_CLOCK_DATE_8_BIN                (void *)(0x0cd42778)
#define   PULL_UP_CLOCK_DATE_9_BIN                (void *)(0x0cd42d78)
#define   PULL_UP_CLOCK_DATE_LINE_BIN             (void *)(0x0cd43278)
#define   PULL_UP_CLOCK_HOUR_BIN                  (void *)(0x0cd433f8)
#define   PULL_UP_CLOCK_MINUTE_BIN                (void *)(0x0cd439f8)
#define   PULL_UP_CLOCK_SECOND_BIN                (void *)(0x0cd442f8)
#define   PULL_UP_CLOCK_WEEK_CH_1_BIN             (void *)(0x0cd445f8)
#define   PULL_UP_CLOCK_WEEK_CH_2_BIN             (void *)(0x0cd44e38)
#define   PULL_UP_CLOCK_WEEK_CH_3_BIN             (void *)(0x0cd45678)
#define   PULL_UP_CLOCK_WEEK_CH_4_BIN             (void *)(0x0cd45f38)
#define   PULL_UP_CLOCK_WEEK_CH_5_BIN             (void *)(0x0cd46c38)
#define   PULL_UP_CLOCK_WEEK_CH_6_BIN             (void *)(0x0cd476f8)
#define   PULL_UP_CLOCK_WEEK_CH_7_BIN             (void *)(0x0cd48278)
#define   PULL_UP_CLOCK_WEEK_EN_1_BIN             (void *)(0x0cd48cf8)
#define   PULL_UP_CLOCK_WEEK_EN_2_BIN             (void *)(0x0cd49c78)
#define   PULL_UP_CLOCK_WEEK_EN_3_BIN             (void *)(0x0cd4a5f8)
#define   PULL_UP_CLOCK_WEEK_EN_4_BIN             (void *)(0x0cd4b278)
#define   PULL_UP_CLOCK_WEEK_EN_5_BIN             (void *)(0x0cd4bd38)
#define   PULL_UP_CLOCK_WEEK_EN_6_BIN             (void *)(0x0cd4c538)
#define   PULL_UP_CLOCK_WEEK_EN_7_BIN             (void *)(0x0cd4d038)
#define   PULL_UP_COMPASS_BG_BIN                  (void *)(0x0cd4df78)
#define   PULL_UP_COMPASS_DIRECTION_ARROW_BIN     (void *)(0x0cd4ee38)
#define   PULL_UP_COMPASS_NUM_0_BIN               (void *)(0x0cd53f78)
#define   PULL_UP_COMPASS_NUM_1_BIN               (void *)(0x0cd54538)
#define   PULL_UP_COMPASS_NUM_2_BIN               (void *)(0x0cd548f8)
#define   PULL_UP_COMPASS_NUM_3_BIN               (void *)(0x0cd54eb8)
#define   PULL_UP_COMPASS_NUM_4_BIN               (void *)(0x0cd554b8)
#define   PULL_UP_COMPASS_NUM_5_BIN               (void *)(0x0cd55978)
#define   PULL_UP_COMPASS_NUM_6_BIN               (void *)(0x0cd55f78)
#define   PULL_UP_COMPASS_NUM_7_BIN               (void *)(0x0cd565f8)
#define   PULL_UP_COMPASS_NUM_8_BIN               (void *)(0x0cd56af8)
#define   PULL_UP_COMPASS_NUM_9_BIN               (void *)(0x0cd57238)
#define   PULL_UP_COMPASS_NUM_DEGREE_BIN          (void *)(0x0cd57878)
#define   PULL_UP_COMPASS_NUM_TILDE_BIN           (void *)(0x0cd57bf8)
#define   PULL_UP_COMPASS_UNIT_CH_E_BIN           (void *)(0x0cd57eb8)
#define   PULL_UP_COMPASS_UNIT_CH_N_BIN           (void *)(0x0cd587b8)
#define   PULL_UP_COMPASS_UNIT_CH_NE_BIN          (void *)(0x0cd59238)
#define   PULL_UP_COMPASS_UNIT_CH_NW_BIN          (void *)(0x0cd5a0f8)
#define   PULL_UP_COMPASS_UNIT_CH_S_BIN           (void *)(0x0cd5af78)
#define   PULL_UP_COMPASS_UNIT_CH_SE_BIN          (void *)(0x0cd5b8b8)
#define   PULL_UP_COMPASS_UNIT_CH_SW_BIN          (void *)(0x0cd5c6b8)
#define   PULL_UP_COMPASS_UNIT_CH_W_BIN           (void *)(0x0cd5d438)
#define   PULL_UP_COMPASS_UNIT_EN_E_BIN           (void *)(0x0cd5dcb8)
#define   PULL_UP_COMPASS_UNIT_EN_N_BIN           (void *)(0x0cd5e178)
#define   PULL_UP_COMPASS_UNIT_EN_NE_BIN          (void *)(0x0cd5e878)
#define   PULL_UP_COMPASS_UNIT_EN_NW_BIN          (void *)(0x0cd5f278)
#define   PULL_UP_COMPASS_UNIT_EN_S_BIN           (void *)(0x0cd601f8)
#define   PULL_UP_COMPASS_UNIT_EN_SE_BIN          (void *)(0x0cd608f8)
#define   PULL_UP_COMPASS_UNIT_EN_SW_BIN          (void *)(0x0cd61278)
#define   PULL_UP_COMPASS_UNIT_EN_W_BIN           (void *)(0x0cd62178)
#define   PULL_UP_HEART_BG_BIN                    (void *)(0x0cd62c78)
#define   PULL_UP_HEART_UNIT_CH_BIN               (void *)(0x0cd73f78)
#define   PULL_UP_HEART_UNIT_EN_BIN               (void *)(0x0cd74878)
#define   PULL_UP_MUSIC_BACK_BIN                  (void *)(0x0cd75178)
#define   PULL_UP_MUSIC_BACK_PRESS_BIN            (void *)(0x0cd756f8)
#define   PULL_UP_MUSIC_BG_BIN                    (void *)(0x0cd75c78)
#define   PULL_UP_MUSIC_FORWARD_BIN               (void *)(0x0cd81f38)
#define   PULL_UP_MUSIC_FORWARD_PRESS_BIN         (void *)(0x0cd824b8)
#define   PULL_UP_MUSIC_START_BIN                 (void *)(0x0cd82a38)
#define   PULL_UP_MUSIC_START_PRESS_BIN           (void *)(0x0cd854b8)
#define   PULL_UP_NAVIGATION_BG_BIN               (void *)(0x0cd87eb8)
#define   PULL_UP_BG_BIN                          (void *)(0x0cdb3d38)
#define   CALENDAR_BIN                            (void *)(0x0cdb6278)
#define   RECENT_APP_ALIPAY_BIN                   (void *)(0x0cdb8ab8)
#define   RECENT_APP_APP_CENTER_BIN               (void *)(0x0cdbb5f8)
#define   RECENT_APP_BO_BIN                       (void *)(0x0cdbd578)
#define   RECENT_APP_BP_BIN                       (void *)(0x0cdc0378)
#define   RECENT_APP_BREATHE_BIN                  (void *)(0x0cdc24b8)
#define   RECENT_APP_BRIGHT_SCREEN_BIN            (void *)(0x0cdc7c38)
#define   RECENT_APP_BS_BIN                       (void *)(0x0cdc9db8)
#define   RECENT_APP_CAL_BIN                      (void *)(0x0cdcc2f8)
#define   RECENT_APP_CAMERA_BIN                   (void *)(0x0cdd2038)
#define   RECENT_APP_CLOCK_BIN                    (void *)(0x0cdd4c78)
#define   RECENT_APP_COMPASS_BIN                  (void *)(0x0cdd7b38)
#define   RECENT_APP_DIAL_BIN                     (void *)(0x0cdd9938)
#define   RECENT_APP_FIND_BIN                     (void *)(0x0cddac78)
#define   RECENT_APP_GAME_BIN                     (void *)(0x0cdddf38)
#define   RECENT_APP_HR_BIN                       (void *)(0x0cde0e38)
#define   RECENT_APP_MAP_BIN                      (void *)(0x0cde5f38)
#define   RECENT_APP_MET_BIN                      (void *)(0x0cde94b8)
#define   RECENT_APP_MSG_BIN                      (void *)(0x0cdeb778)
#define   RECENT_APP_MUSIC_BIN                    (void *)(0x0cdefef8)
#define   RECENT_APP_PRESSURE_BIN                 (void *)(0x0cdf56f8)
#define   RECENT_APP_QQ_BIN                       (void *)(0x0cdfba78)
#define   RECENT_APP_QR_BIN                       (void *)(0x0cdfcfb8)
#define   RECENT_APP_RECORD_BIN                   (void *)(0x0cdff1b8)
#define   RECENT_APP_SETTING_BIN                  (void *)(0x0ce02038)
#define   RECENT_APP_SIRI_BIN                     (void *)(0x0ce06478)
#define   RECENT_APP_SLEEP_BIN                    (void *)(0x0ce0d378)
#define   RECENT_APP_SPORT_BIN                    (void *)(0x0ce10b78)
#define   RECENT_APP_STEP_BIN                     (void *)(0x0ce135b8)
#define   RECENT_APP_STOCK_MARKET_BIN             (void *)(0x0ce187f8)
#define   RECENT_APP_TEL_BIN                      (void *)(0x0ce1c478)
#define   RECENT_APP_TEMPERATURE_BIN              (void *)(0x0ce21f38)
#define   RECENT_APP_THEME_BIN                    (void *)(0x0ce24c38)
#define   RECENT_APP_TIMER_BIN                    (void *)(0x0ce27178)
#define   RECENT_APP_TRAJECTORY_BIN               (void *)(0x0ce29ff8)
#define   RECENT_APP_WEATHER_BIN                  (void *)(0x0ce2cb38)
#define   RECENT_APP_WEATHER_PRESSURE_BIN         (void *)(0x0ce2f5f8)
#define   RECENT_APP_WOMAN_BIN                    (void *)(0x0ce351f8)
#define   PULL_UP_STEP_CAL_NUM_0_BIN              (void *)(0x0ce37178)
#define   PULL_UP_STEP_CAL_NUM_1_BIN              (void *)(0x0ce375f8)
#define   PULL_UP_STEP_CAL_NUM_2_BIN              (void *)(0x0ce379b8)
#define   PULL_UP_STEP_CAL_NUM_3_BIN              (void *)(0x0ce37db8)
#define   PULL_UP_STEP_CAL_NUM_4_BIN              (void *)(0x0ce38278)
#define   PULL_UP_STEP_CAL_NUM_5_BIN              (void *)(0x0ce38678)
#define   PULL_UP_STEP_CAL_NUM_6_BIN              (void *)(0x0ce38b38)
#define   PULL_UP_STEP_CAL_NUM_7_BIN              (void *)(0x0ce38ff8)
#define   PULL_UP_STEP_CAL_NUM_8_BIN              (void *)(0x0ce39378)
#define   PULL_UP_STEP_CAL_NUM_9_BIN              (void *)(0x0ce398b8)
#define   PULL_UP_STEP_DIS_NUM_0_BIN              (void *)(0x0ce39d78)
#define   PULL_UP_STEP_DIS_NUM_1_BIN              (void *)(0x0ce3a1f8)
#define   PULL_UP_STEP_DIS_NUM_2_BIN              (void *)(0x0ce3a5b8)
#define   PULL_UP_STEP_DIS_NUM_3_BIN              (void *)(0x0ce3a9b8)
#define   PULL_UP_STEP_DIS_NUM_4_BIN              (void *)(0x0ce3ae78)
#define   PULL_UP_STEP_DIS_NUM_5_BIN              (void *)(0x0ce3b278)
#define   PULL_UP_STEP_DIS_NUM_6_BIN              (void *)(0x0ce3b738)
#define   PULL_UP_STEP_DIS_NUM_7_BIN              (void *)(0x0ce3bbf8)
#define   PULL_UP_STEP_DIS_NUM_8_BIN              (void *)(0x0ce3bf78)
#define   PULL_UP_STEP_DIS_NUM_9_BIN              (void *)(0x0ce3c4b8)
#define   PULL_UP_STEP_DIS_NUM_DOT_BIN            (void *)(0x0ce3c978)
#define   PULL_UP_STEP_ICON_BIN                   (void *)(0x0ce3caf8)
#define   PULL_UP_STEP_STEPS_NUM_0_BIN            (void *)(0x0ce3f7f8)
#define   PULL_UP_STEP_STEPS_NUM_1_BIN            (void *)(0x0ce3fc78)
#define   PULL_UP_STEP_STEPS_NUM_2_BIN            (void *)(0x0ce40038)
#define   PULL_UP_STEP_STEPS_NUM_3_BIN            (void *)(0x0ce40438)
#define   PULL_UP_STEP_STEPS_NUM_4_BIN            (void *)(0x0ce408f8)
#define   PULL_UP_STEP_STEPS_NUM_5_BIN            (void *)(0x0ce40cf8)
#define   PULL_UP_STEP_STEPS_NUM_6_BIN            (void *)(0x0ce411b8)
#define   PULL_UP_STEP_STEPS_NUM_7_BIN            (void *)(0x0ce41678)
#define   PULL_UP_STEP_STEPS_NUM_8_BIN            (void *)(0x0ce419f8)
#define   PULL_UP_STEP_STEPS_NUM_9_BIN            (void *)(0x0ce41f38)
#define   PULL_UP_WEATHER_BG_BIN                  (void *)(0x0ce424f8)
#define   PULL_UP_WEATHER_CLOUDY_BIN              (void *)(0x0ce430b8)
#define   PULL_UP_WEATHER_NUM_0_BIN               (void *)(0x0ce43e38)
#define   PULL_UP_WEATHER_NUM_1_BIN               (void *)(0x0ce442f8)
#define   PULL_UP_WEATHER_NUM_2_BIN               (void *)(0x0ce445f8)
#define   PULL_UP_WEATHER_NUM_3_BIN               (void *)(0x0ce44a78)
#define   PULL_UP_WEATHER_NUM_4_BIN               (void *)(0x0ce44f78)
#define   PULL_UP_WEATHER_NUM_5_BIN               (void *)(0x0ce45338)
#define   PULL_UP_WEATHER_NUM_6_BIN               (void *)(0x0ce45838)
#define   PULL_UP_WEATHER_NUM_7_BIN               (void *)(0x0ce45d78)
#define   PULL_UP_WEATHER_NUM_8_BIN               (void *)(0x0ce46178)
#define   PULL_UP_WEATHER_NUM_9_BIN               (void *)(0x0ce46778)
#define   PULL_UP_WEATHER_NUM_C_BIN               (void *)(0x0ce46c78)
#define   PULL_UP_WEATHER_NUM_F_BIN               (void *)(0x0ce47238)
#define   PULL_UP_WEATHER_NUM_LINE_BIN            (void *)(0x0ce47678)
#define   PULL_UP_WEATHER_RAIN_BIN                (void *)(0x0ce477f8)
#define   PULL_UP_WEATHER_SNOW_BIN                (void *)(0x0ce483b8)
#define   PULL_UP_WEATHER_SUNNY_BIN               (void *)(0x0ce48ef8)
#define   PULL_UP_WEATHER_UNKNOWN_BIN             (void *)(0x0ce4b038)
#define   JINGYINGUAN_BIN                         (void *)(0x0ce4b8f8)
#define   JINGYINKAI_BIN                          (void *)(0x0ce5d8b8)
#define   JUYUANMOSHIGUAN_BIN                     (void *)(0x0ce6f878)
#define   JUYUANMOSHIKAI_BIN                      (void *)(0x0ce81838)
#define   LIANGDUGUAN_BIN                         (void *)(0x0ce937f8)
#define   LIANGDUKAI_BIN                          (void *)(0x0cea57b8)
#define   LINGSHENGGUAN_BIN                       (void *)(0x0ceb7778)
#define   LINGSHENGKAI_BIN                        (void *)(0x0cec9738)
#define   MUTE_OFF_BIN                            (void *)(0x0cedb6f8)
#define   MUTE_ON_BIN                             (void *)(0x0ceeb9f8)
#define   NAOZHONGGUAN_BIN                        (void *)(0x0cefbcf8)
#define   NAOZHONGKAI_BIN                         (void *)(0x0cf0dcb8)
#define   NO_DISTURB_OFF_BIN                      (void *)(0x0cf1fc78)
#define   NO_DISTURB_ON_BIN                       (void *)(0x0cf2ff78)
#define   RECT_221_269_BIN                        (void *)(0x0cf40278)
#define   RING_OFF_BIN                            (void *)(0x0cf7a378)
#define   RING_ON_BIN                             (void *)(0x0cf8a678)
#define   SET_OFF_BIN                             (void *)(0x0cf9a978)
#define   SET_ON_BIN                              (void *)(0x0cfaac78)
#define   SHEZHIGUAN_BIN                          (void *)(0x0cfbaf78)
#define   SHEZHIKAI_BIN                           (void *)(0x0cfccf38)
#define   SHIZHONGGUAN_BIN                        (void *)(0x0cfdeef8)
#define   SHIZHONGKAI_BIN                         (void *)(0x0cff0eb8)
#define   SHOUDIANTONGGUAN_BIN                    (void *)(0x0d002e78)
#define   SHOUDIANTONGKAI_BIN                     (void *)(0x0d014e38)
#define   SIGNAL_OFF_BIN                          (void *)(0x0d026df8)
#define   SIGNAL_ON_BIN                           (void *)(0x0d0370f8)
#define   SIMKAI_SIZE24_BITS4_FONT_BIN            (void *)(0x0d0473f8)
#define   THEATRE_OFF_BIN                         (void *)(0x0d060738)
#define   THEATRE_ON_BIN                          (void *)(0x0d070a38)
#define   VIBRATE_OFF_BIN                         (void *)(0x0d080d38)
#define   VIBRATE_ON_BIN                          (void *)(0x0d091038)
#define   WATCH_OFF_BIN                           (void *)(0x0d0a1338)
#define   WATCH_ON_BIN                            (void *)(0x0d0b1638)
#define   WURAOGUAN_BIN                           (void *)(0x0d0c1938)
#define   WURAOKAI_BIN                            (void *)(0x0d0d38f8)
#define   XINHAOGUAN_BIN                          (void *)(0x0d0e58b8)
#define   XINHAOKAI_BIN                           (void *)(0x0d0f7878)
#define   ZHENDONGGUAN_BIN                        (void *)(0x0d109838)
#define   ZHENDONGKAI_BIN                         (void *)(0x0d11b7f8)

#endif
